// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the MyFirstModule module

	public static java.util.List<myfirstmodule.proxies.Content> dS_GetCarousel(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.DS_GetCarousel", params);
			java.util.List<myfirstmodule.proxies.Content> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.Content>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.Content.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean iVK_EntityTest_Show(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			return (Boolean)Core.execute(context, "MyFirstModule.IVK_EntityTest_Show", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_NewBannerthing(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "MyFirstModule.IVK_NewBannerthing", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_SaveBanner(IContext context, myfirstmodule.proxies.Content _content)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Content", _content == null ? null : _content.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_SaveBanner", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}